### ISSUE TITLE
Attach or generate changelog

### ISSUE THREAD

**Issue by 3Hren** [mmstick/cargo-deb#10]
Hi! Thanks for this project!

Is there any possibility to attach/generate debian changelog?

**Comment by mmstick** [comment]
No, that would require a PR, and I'm not maintaining this project anymore, but if you'd like to implement support for it, you may. I'm leaving this up to the Debian team to produce tools of their own, which they are doing.

**Comment by 3Hren** [comment]
Oh, that's unfortunate. Thanks for instant reaction.

**Comment by pornel** [comment]
How do you imagine that working?

I'm not sure what to implement here, because Cargo doesn't have any standard way of maintaining changelogs.

**Comment by pornel** [comment]
https://github.com/rust-lang/cargo/issues/2188

**Comment by 3Hren** [comment]
The most naive approach is to maintain debian/changelog manually. More
complex is to have Changelog.md, which is more-less standardized
вт, 1 авг. 2017 г. в 14:34, Kornel <notifications@github.com>:

**Comment by pornel** [comment]
OK, that might work:

```toml
[package.metadata.deb]
changelog = "file"
```

would you like to implement it?
