### ISSUE TITLE
Packaging a service

### ISSUE THREAD

**Issue by TotalKrill** [mmstick/cargo-deb#100]
I want to package a binary that is being used as a service. I have my package.service located in the project folder under scripts/package.service. 

Is there any example of how I would go about in cargo deb to get the software service file included, installed and enabled?

**Comment by kornelski** [comment]
You can. You will need to add `assets = [` to `Cargo.toml` listing files you want to package. See the second example in the readme.

**Comment by TotalKrill** [comment]
Yeah, I have added it to assets and i can see that it gets into the package, however, I think that when creating deb packages otherwise, they do some automagic that enables services automatically somehow. When I add the service unit file with the `assets = [`, I will manually have to enable the service. 

But some other threads I found highlighted some problems in doing stuff like this using postinst, etc that depended on systemctl. So before I started jumping down this rabbit-hole, i was thinking I could ask here.

This issue describes what I want. 
[debian service](https://unix.stackexchange.com/questions/423069/postinst-maintainer-script-stops-systemd-unit-file-from-starting-automatically-o)

From this one, I tried to adding the `maintainers-script = "folder"` tag, and put the service file in there in the hopes it would get included in the package creation, and in a similar way enable the service on installation.

If i have to start creating postinst and preinst scripts, an example would be very helpful so that I could know what to expect.

**Comment by kornelski** [comment]
There's nothing magic in deb for services. The services are "automatically" enabled by putting `.service` file in a directory read by systemd.

**Comment by TotalKrill** [comment]
So if i wanted to enable on installation it I would have to use the postinst scripts, gotcha

**Comment by kornelski** [comment]
No? I think mere existence of a .service file in `/etc` is enough.

**Comment by TotalKrill** [comment]
Yeah, I tried that. It is recognized by systemd so that I can run "systemctl enable myservice". But it is not enabled and/or started by itself, I need to run commands for that

**Comment by fredszaq** [comment]
Hi!

I usually do that using the `postinst`, `postrm` and `prerm` maintainer scripts of the debian package

Here are the files I use (click to expand) :
<details><summary> <code>debian/postinst</code> </summary>
<p>

```sh
#!/bin/sh

# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask snips-dialogue.service > /dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled snips-dialogue.service
then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable my-service.service > /dev/null || true
	deb-systemd-invoke start my-service
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state my-service.service > /dev/null || true
fi
```
</p>
</details>

<details><summary><code>debian/postrm</code></summary>
<p>

```sh
#!/bin/sh

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask my-service.service >/dev/null
	fi
fi
```

</p>
</details>


<details><summary><code>debian/prerm</code></summary>
<p>

```sh
#!/bin/sh

deb-systemd-invoke stop my-service
```
</p>
</details>


Put them in a directory named `debian` and the root of you crate (I also put my service file in this folder). you then need to register the maintainer scripts and the service file for cargo-deb to pick them up: 
```toml
[package.metadata.deb]
#...
maintainer-scripts="debian"
assets = [
    ["debian/my-service.service", "/lib/systemd/system/my-service.service", "644"], 
    #...
]
```

**Comment by Kixunil** [comment]
I didn't need to do anything extra when packaging something with `.service` file. Debian trigger system handles it. I guess there's a problem with the service file?

**Comment by ximon18** [comment]
When packaging using Debian packaging tools such as debhelper the dh_installsystemd command can be used to cause systemd unit activation related autoscript fragments to be inserted into maintainer scripts in place of the `#DEBHELPHER#` token. Such logic doesn't exist in cargo deb, you have to provide the maintainer scripts and the correct logic inside them yourself. However with my PR #135 cargo deb can detect the unit files and augment/generate the maintainer scripts for you just like dh_installsystemd does.

**Comment by kornelski** [comment]
Please test the latest beta.

https://github.com/mmstick/cargo-deb/blob/master/systemd.md
