### ISSUE TITLE
Version string gets mangled

### ISSUE THREAD

**Issue by vorner** [mmstick/cargo-deb#103]
Hello

I have a project with version string containing a dash, eg `version = "0.1.18-53"` in the `Cargo.toml`. However, the package name I get from it is `name_0.1.18~53_arch.deb`. Is there a particular reason why my dash gets changed? It's causing confusion in our internal system that expects dashes :-(.

I'm using cargo-deb 1.20.

Thank you

**Comment by kornelski** [comment]
That was https://github.com/mmstick/cargo-deb/pull/102

**Comment by vorner** [comment]
Hmm. But we don't use the dash in the semver meaning, it's a build number. Is there a way to opt out of this and tell `cargo deb` to keep it as it is?

**Comment by kornelski** [comment]
`--deb-version` command line flag is currently the way to opt out

**Comment by kornelski** [comment]
Also you can use `revision` in `Cargo.toml` to add a number to the version

```
version = "0.1.18"
…
revision = "53"
```

**Comment by kornelski** [comment]
I've made it accept numeric suffixes as-is

**Comment by vorner** [comment]
Thank you, yes indeed this works.
