### ISSUE TITLE
Documentation and code disagree about maintainerscripts and conffiles

### ISSUE THREAD

**Issue by zwenna** [mmstick/cargo-deb#104]
Commit 340958f5aa ("Documented hidden features") documented the "maintainer-scripts" and "conf-files" features in README.md, but AFAICT the implementation actually uses "maintainer_scripts" and "conf_files", respectively.

**Comment by kornelski** [comment]
The code relies on Serde's `kebab-case` transform.

**Comment by zwenna** [comment]
Thanks for the fast reply. I was fooled by mssing maintainerscripts in https://github.com/jwilm/alacritty/issues/2554.
