### ISSUE TITLE
Are release profiles supported in a cargo workspace ?

### ISSUE THREAD

**Issue by flocknetworks** [mmstick/cargo-deb#113]
Is [profile.release] supported in a cargo workspace ?

[profile.release]
debug = true

RUSTFLAGS="-D warnings" cargo build --release -p flockrsd
has symbols

RUSTFLAGS="-D warnings" cargo deb -p flockrsd
does not have symbols

flock@flocknet:~$ ls -l flockrsd /usr/bin/flockrsd
-rwxr-xr-x 1 flock flock 43519440 Nov 11 14:48 flockrsd
-rwxr-xr-x 1 root  root   3115544 Nov 11 14:53 /usr/bin/flockrsd

thanks for any help,
Nick

**Comment by kornelski** [comment]
Nope. `cargo metadata` doesn't expose profiles, and `cargo-deb` fills in missing information only from `Cargo.toml` of the package.

**Comment by flocknetworks** [comment]
thanks for the info, i can use this as a work around
RUSTFLAGS="-D warnings" cargo build --release -p flockrsd && cargo deb -p flockrsd --no-build --no-strip

**Comment by flocknetworks** [comment]
I guess the correct fix for this would be to move the metadata.deb information up into the virtual manifest / workspace root ?
Similar to how the profile information was moved ?
https://github.com/rust-lang/cargo/issues/3206

**Comment by kornelski** [comment]
I'm not sure about it. Some properties are very package-specific. Maybe it should read both, and combine them? Or only read profiles from the workspace, to emulate Cargo.

**Comment by flocknetworks** [comment]
I think combining the properties for all the different combinations would be very difficult.  Also following what Cargo does in general is probably going to be easier.  So I'd say in a workspace only read the workspace settings.
Anyway I have a workaround so will close this issue.  Thanks for the crate, all the maintainer-script support etc works great.
