### ISSUE TITLE
Build one deb per workspace member

### ISSUE THREAD

**Issue by segfaultsourcery** [mmstick/cargo-deb#114]
This crate is fantastic, however I am missing one feature, namely multi package builds. I'm using workspaces, and I would like each member to turn into a separate deb file. The only way I seem to be able to achieve this is by building the packages separately, then copying the deb file from the target/debian/ folder. I have to copy after each build completes, since target/debian is deleted before building.

Is there already support for what I want? If not, I can try to write it myself.

**Comment by kornelski** [comment]
You can use `-o` to put .deb files elsewhere, and `-p` to specify package name.

I've updated the code to allow multiple packages to build at the same time.

Here's previous discussion: #49

**Comment by segfaultsourcery** [comment]
Fantastic! Thank you very much.

**Comment by segfaultsourcery** [comment]
It's worth noting that multi invocation doesn't work with the --install flag due to dpkg's locking.

Something like this would break:
```bash
$ cargo deb --install --package a & cargo deb --install --package b
...
cargo-deb: installation failed, because dpkg -i returned error
...
```


Other than that, I just ran some tests of my own on it, and it's working perfectly! Thank you very much!
