### ISSUE TITLE
Support for multiple packages from single crate

### ISSUE THREAD

**Issue by tglman** [mmstick/cargo-deb#123]
Hi,

The rust crate support the possibility to produce multiple binaries, and I have this case, would be cool if I could produce multiple packages each of it with a single binary, as today cargo deb allow only to generate one package, and at most a variant of the same package, is there any plan to support this ?

by the way, this is already a great project as it is.

Regards

**Comment by kornelski** [comment]
Cargo is a bit ambiguous about what is a crate and what is a workspace, but I'd say that if the binaries are separate enough that they don't belong in a single deb, they they also don't belong to a single crate.

Split them into a workspace, and build with `-p`. I wouldn't mind expanding workspace support: #49

**Comment by tglman** [comment]
Hi,

Fair point, I haven't had chance to try the workspace setup, will try out and report.

Thanks
Regards

**Comment by tglman** [comment]
Hi, 

The workspace setup works perfectly thanks, closing this.

Regards
