### ISSUE TITLE
Allow setting a ~suffix

### ISSUE THREAD

**Issue by kpcyrd** [mmstick/cargo-deb#127]
I'm maintaining a repo of packages that I also maintain in debian, since I can upload new versions much faster than I could in debian. Since the packages are not identical and to avoid hard to debug situations I'd prefer to be able to configure a ~ suffix (not sure what the proper term is, I found a description [here](https://unix.stackexchange.com/a/230921)) that is appended to the version to make sure apt prefers the version in debian main over the one I've shipped in my private repo at some point in the past. I'd like to configure this in my Cargo.toml in case somebody built the package on their own with `cargo deb`.

This is a common thing to do for backports, using [reprepro][1] as an example:

- stretch-backports has `5.3.0-1~bpo9+1`
- buster has `5.3.0-1`

apt considers `5.3.0-1~bpo9+1 < 5.3.0-1`, so when upgrading from stretch to buster it would replace the backported package with the one from buster.

[1]: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=reprepro

**Comment by kornelski** [comment]
Is deb-version not sufficient?

https://github.com/mmstick/cargo-deb#custom-version-strings
