### ISSUE TITLE
Question: Default "$auto" depends adds unneeded dependencies?

### ISSUE THREAD

**Issue by ms-jpq** [mmstick/cargo-deb#129]
Hi there,

Really cool project, but I ran into some hiccup using it in a CI when I got some depedencies that broke things. I dug around a bit and found some how the deb requires `libgcc1` and `libc6`.

This is kinda werid, since my naked binary built with `x86_64-unknown-linux-gnu` do not have any dependencies. 

Is it safe for me to just ignore those two like so?

```toml
[package.metadata.deb]
depends = ""
```

Thanks!

**Comment by kornelski** [comment]
AFAIK these dependencies are correct and necessary. They may be so obvious that they're not usually mentioned, but the binary will fail to launch without these libraries on the system.

Run `ldd` on your binary and see what it links to. You'll see "libgcc_s.so.1" and "libc.so.6".

**Comment by kornelski** [comment]
I've found that libgcc_s is supposed to always be installed according to LSB, so maybe it's too much to make it a package dependency.

**Comment by ms-jpq** [comment]
ahh I see, thank you for the explanation!
