### ISSUE TITLE
How to override package name?

### ISSUE THREAD

**Issue by lilith** [mmstick/cargo-deb#136]
How do I override the package name? Currently it takes the crate name which is not what I want, and due to crate name conflicts I can't change the crate name. 

```
[package]
name = "imageflow_abi"
version = "0.1.0"
authors = ["Lilith River <lilith@imazen.io>"]
workspace = "../"
build = "build.rs"
edition = "2018"

[lib]
name = "imageflow"
doc = true
crate-type = ["cdylib"]
doctest = false

[dependencies]
libc = "0.2"
```

**Comment by ximon18** [comment]
@lilith: My apologies if I misunderstand your question, but you can set the package name in the Cargo deb metadata as shown [in the README here](https://github.com/mmstick/cargo-deb#packagemetadatadeb-options), e.g.:

```
[package.metadata.deb]
name = "some package name"
```

**Comment by lilith** [comment]
I can't believe I missed that. Thank you so much!
