### ISSUE TITLE
`dpkg -i` fails if readme has an indented long word

### ISSUE THREAD

**Issue by taotao54321** [mmstick/cargo-deb#142]
Related to #141.

If readme file has an indented long (no-spaced) word, the extended description will have an whitespace-only line, and `dpkg -i` fails.

For example, I failed to install [alacritty](https://github.com/alacritty/alacritty) due to this issue. The [README.md](https://raw.githubusercontent.com/alacritty/alacritty/master/README.md) contains these lines:

```
  <img width="600"
       alt="Alacritty running vim inside tmux"
       src="https://cloud.githubusercontent.com/assets/4285147/21585004/2ebd0288-d06c-11e6-95d3-4a2889dbbd6f.png">
```

and the last line causes the problem. `split_by_chars()` splits lines with `split(' ')`, so for example, "  indented" is split into `["", "", "indented"]`. And the last word exceeds limit, the function appends a whitespace-only line.

I wanted to fix this, but it seems not so obvious to me how to treat such cases (indentations should be kept or not?). Anyway, I post this as an issue.

**Comment by kornelski** [comment]
The goal is to preserve indentations, and generally preserve everything about the input format.

**Comment by kornelski** [comment]
Would it suffice to force break of long lines? https://github.com/mmstick/cargo-deb/blob/f4f455f61baa80c359c69e5e784798f82c64fce5/src/wordsplit.rs#L21

**Comment by taotao54321** [comment]
> Would it suffice to force break of long lines?

I'm not sure I correctly understand your words due to my poor English skill, but the current code is not sufficient to install alacritty.
The line of the issue is expanded like below.

before:

```
       src="https://cloud.githubusercontent.com/assets/4285147/21585004/2ebd0288-d06c-11e6-95d3-4a2889dbbd6f.png">
```

after (`_` means a space character):

```
_______
src="https://cloud.githubusercontent.com/assets/4285147/21585004/2ebd0288-d06c-11e6-95d3-4a2889dbbd6f.png">
```

> The goal is to preserve indentations, and generally preserve everything about the input format.

Thank you. I understand the goal.

My concern is that indented lines are not so friendly to line breaking. For example, `README.md` sometimes contains code block like this:

```
    very_very_very_long_function_name(1, 2, 3);
```

If the current code is fixed naively to keep indentation, this will be expanded like:

```
    very_very_very_long_function_name(1,
2, 3);
```

This is a bit ugly, and may become incorrect codes in line-oriented languages like Python. So, I consider two options:

* Apply the naive fix, and don't care the small uglyness like above.
* Do not break indented lines.

I personally like the latter, because long lines are relatively rare, and the current code does not break very long word anyway.
Would you give me your thoughts?

**Comment by kornelski** [comment]
Oh, now I get it.

So it need special handling when the first word after indentation doesn't fit on the line, and keep it (or force-wrap it).

I'm not sure if Debian allows exceeding line length. It may be necessary to force wrapping.

I wouldn't worry too much about breaking python code - the description is for reading by humans, not for copying code.

Does https://lib.rs/crates/textwrap handle wrapping better? If so, we could use that create and then correct only empty lines to match debian syntax.

**Comment by taotao54321** [comment]
Hm, I'm no familiar with debian packaging, but I researched as possible. For implementation, I used `dpkg` 1.20.5 on debian testing.

In implementation, `dpkg` seems to accept any length of line as extended description.
In specification, I found these documents:

* https://www.debian.org/doc/debian-policy/ch-controlfields.html#description
* https://www.debian.org/doc/debian-policy/ch-binary.html#s-descriptions
* https://www.debian.org/doc/manuals/maint-guide/dreq.html#control

In summary, debian policy requires extended description lines as below:

* They must have at least one non-whitespace character.
* They must not contain any tab character.

And, debian policy seems to say nothing about the length of lines in extended description. So, I'm wondering whether the current line breaking process is really needed. Indeed, tools like `aptitude` automatically word-wraps successive lines. As for extended description, it seems to be sufficient to me just avoiding whitespace-only lines and replacing tab characters in a certain way.
But I think it would be better to ask some experienced debian package maintainer for advice if possible.

By the way:

* If we do force wrapping with hyphen (`textwrap` seems to have this feature), `aptitude` doesn't properly restore those lines.
* Debian policy says single line synopsis (`options.description`) *should* be under 80 characters (and maintainer's guide seems to recommend up to 60 chars). But in implementation, `dpkg` seems to accept longer single line synopsis.)

**Comment by ximon18** [comment]
> I'm not sure I correctly understand your words due to my poor English skill, but the current code is not sufficient to install alacritty.

Unrelated to the issue at hand, as a native English speaker I just wanted to say that I find your English to be very impressive!

**Comment by kornelski** [comment]
Ok, if long lines are allowed, then it should be OK to not wrap the problematic line.

**Comment by taotao54321** [comment]
Okay, I made a pull request #143 (some tests added). The implementation is somewhat inefficient, and the specification of conversion might be still debatable, but I will leave those to experts.
