### ISSUE TITLE
get_package_name is broken for /usr/lib/x86_64-linux-gnu/libGL.so.1

### ISSUE THREAD

**Issue by H-M-H** [mmstick/cargo-deb#144]
On debian stretch dpkg reports:
```console
> dpkg -S /usr/lib/x86_64-linux-gnu/libGL.so.1    
diversion by glx-diversions from: /usr/lib/x86_64-linux-gnu/libGL.so.1
diversion by glx-diversions to: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGL.so.1
libgl1-mesa-glx:amd64: /usr/lib/x86_64-linux-gnu/libGL.so.1
```
Which results in
https://github.com/mmstick/cargo-deb/blob/94ba8f33b943a232bb12f664bbe5c070c7ecc430/src/dependencies.rs#L84-L92
parsing it as the package `diversion by glx-diversions from`, which obviously is not the desired behavior.

**Comment by kornelski** [comment]
Fixed, thanks
