### ISSUE TITLE
[Question] Specifying multiple packages in 'depends'

### ISSUE THREAD

**Issue by Chaostheorie** [mmstick/cargo-deb#150]
Hey!

I'm trying to build a application which requires more than one package (`live-build`, `gnome-keyring`, ...) with depends. It gives an syntax error when separating them with spaces or commas. This field is supposed to be a string so I couldn't use a sequence either.
Can anyone help me out with the syntax for such a case? I haven't found anything regarding this usecase in the examples.

Thanks in advance!

**Comment by kornelski** [comment]
Comma-separated list should work. Can you specify what is not working?

**Comment by Chaostheorie** [comment]
@kornelski Thank you for the help.
 It seems like I had a `.` instead of  a whitespace when testing with comma-separated.  Error on my side
