### ISSUE TITLE
.a libs not stripped

### ISSUE THREAD

**Issue by kpp** [mmstick/cargo-deb#155]
Whereas .so are stripped.

**Comment by kpp** [comment]
strip is called with `--strip-unneeded`. I was wrong. BTW is it enough to strip out source code?

**Comment by kornelski** [comment]
I don't think stripping of `.a` is even possible. `.a` is just a collection of unlinked object files `.o`, and if you strip their symbols, you won't be able to link them any more.

Source code is never included the executables. Debug information contains only locations in code (like line/column), not the code.

Independent of debug info, Rust also includes a bit of information about types and source code locations in panic messages.
