### ISSUE TITLE
Specify optional dependencies as Recommends / Suggests

### ISSUE THREAD

**Issue by jamesmcm** [mmstick/cargo-deb#159]
According to: https://www.debian.org/doc/debian-policy/ch-relationships.html 

One should specify optional dependencies as Recommends / Suggests / Enhances, etc. - is it possible to do this in cargo-deb ?

Thanks for the great package!

**Comment by kornelski** [comment]
It's not, but it could be added. 

Current processing of dependencies is complicated by the fact that automatic deps are supported. But if you ignore the auto bit, it's a matter of reading the list from cargo metadata and printing them in the control file. 
Give it a try.
