### ISSUE TITLE
Add support for "Recommends" section

### ISSUE THREAD

**Issue by nirvdrum** [mmstick/cargo-deb#163]
Somewhat related to #162, it would be helpful if a package could declare a list of recommended packages to install as well. Using the "Recommends" section allows a package to declare an optional, but helpful, dependency and gives the installer of the package the discretion to install the package along with its recommendations or just with its required dependencies.

**Comment by kornelski** [comment]
Yeah. If it's just a field without any auto logic behind, it should be straightforward. Give it a try.
