### ISSUE TITLE
Use uniform compression

### ISSUE THREAD

**Issue by guillemj** [mmstick/cargo-deb#174]
[ I stumbled over this project and got curious about its implementation and conformance level, so I've done a quick review pass, and I'll be filing several issues about that. :) ]

Since dpkg 1.19.0, dpkg-deb uses uniform compression by default (see [dpkg-deb man page](https://manpages.debian.org/dpkg-deb)), that is, using the same compressor for both control.tar and data.tar. I think it would make sense to do the same here.

**Comment by kornelski** [comment]
Is this backwards-compatible? I'm still occasionally using stretch, which has an older version of dpkg.

control.tar is relatively small, so it's not that big of a deal.

**Comment by guillemj** [comment]
dpkg-deb gained control.tar.xz support in 1.17.6 (see [deb(5) man page](https://manpages.debian.org/unstable/deb)), which was the [release series for jessie](https://wiki.debian.org/Teams/Dpkg/FAQ#Q:_What_is_the_latest_dpkg_version_on_each_Debian_release.3F).

In my mind this not as much as a size concern but of using the same compressor to try to make the format simpler conceptually, even though obviously dpkg-deb will need to support non-uniform binary packages indefinitely, but that could change for say a 3.0 format or similar. :)

**Comment by kornelski** [comment]
Oh, in that case that's great.

**Comment by kornelski** [comment]
Done in e4764b61a62ce946eaa63f066688c78d7de3e952
