### ISSUE TITLE
Emits source-only fields for the generated binary control files

### ISSUE THREAD

**Issue by guillemj** [mmstick/cargo-deb#175]
The generated .deb archives contain fields that are specific to source packages, and do not belong in binary packages, as documented in the [deb-control man page](https://manpages.debian.org/deb-control). Namely:

  * Vcs-_*_
  * Standards-Version
  * Build-Depends

**Comment by kornelski** [comment]
I prefer to keep Vcs-Browser, because repo URL is usually important for Rust crates.

**Comment by guillemj** [comment]
Yeah, it should not hurt. I don't think though any of the automated tools that make use of such fields would notice it being present in the binary package. Of course that does not preclude humans from using them. :)
