### ISSUE TITLE
Guidance on how to build multiple versions of same .deb

### ISSUE THREAD

**Issue by julianandrews** [mmstick/cargo-deb#186]
I've got a project where I need to install assets to one of two locations, depending on the distribution version (assets go to `/usr/lib` for Buster/Hirsute, and to `/usr/libexec/` for Bullseye/Impish).

Is there a good way to build both packages from the same config? I tried using variants, but I want the package name to stay the same.

**Comment by kornelski** [comment]
Unfortunately there isn't.

**Comment by apiraino** [comment]
@julianandrews I think you can create a "base" build and using variants build for different environments. Example:

```
[package.metadata.deb]
# common .deb name (e.g. my-project_x.y.z_amd64.deb)
name = "my-project"

[package.metadata.deb.variants.buster]
assets = [
       ["assets/*", "usr/lib/", "664"]

[package.metadata.deb.variants.bullseye]
assets = [
       ["assets/*", "usr/libexec/", "664"]
```

hth

**Comment by julianandrews** [comment]
@apiraino - that seems to work. Thanks!
