### ISSUE TITLE
Publish on crates.io for easy install via cargo install

### ISSUE THREAD

**Issue by Drakulix** [mmstick/cargo-deb#2]
Getting cargo-deb is a bit of a hassle right now. Especially if you would like to build your artifacts/debs automatically on e.g. travis, you need to checkout cargo-deb and build it at first, then modify the path to include it, before you may package your own crate.

This could be so much easier, if it would be possible to do a simple `cargo install cargo-deb`.

**Comment by mmstick** [comment]
You can use `cargo install` already. This is effectively what crates in crates.io do behind the scenes.

```sh
cargo install --git https://github.com/mmstick/cargo-deb/
```

**Comment by Drakulix** [comment]
Oh I did not know about the git flag, thanks!

**Comment by dead10ck** [comment]
@mmstick even so, it's better to get your crates on crates.io for better community visibility, ease of install, and versioning safety.

**Comment by mmstick** [comment]
@dead10ck For as long as this application relies on git repositories, that will not be possible. I would need for the tar-rs crate to have the issue of creating hidden directories fixed and a version released on crates.io to point to.

**Comment by glennpratt** [comment]
alexcrichton/tar-rs#69

**Comment by pornel** [comment]
I second that. I was surprised that `cargo install cargo-deb` doesn't work. All other Cargo tools I'e seen are installed this way, so this is what I expect. 

Is there any technical reason why this crate can't be published?

**Comment by pornel** [comment]
This will be fully resolved when https://github.com/alexcrichton/tar-rs/pull/121 is published
In the meantime 93b451967b61df5e72291aded45ad0232a34e3f5 contains a workaround
