### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by herrernst** [mmstick/cargo-deb#24]
In a constrained container with 1 GB RAM, cargo-deb has not enough memory:
```
cargo deb --no-build 
warning: extended-description field missing. Using README.md, but markdown may not render well.
cargo-deb: Command ar failed to launch
  because: Cannot allocate memory (os error 12)
```
(Building a large project with cargo before works though.)

**Comment by pornel** [comment]
The archive is created in memory, so you'll need enough RAM to hold entire uncompressed package in memory + 2 * size of compressed package.
