### ISSUE TITLE
parsing "depends" string

### ISSUE THREAD

**Issue by octomike** [mmstick/cargo-deb#25]
So https://github.com/mmstick/cargo-deb/blob/d5e7d522927b1409cf495db8e6b9d312a85994ba/src/manifest.rs#L102 uses a very simple approach to parsing a depends string.
I guess this is just a preliminary approach, because it utterly breaks on any real world dependency string.

Take for example the `mutt` dependencies from the debian doc that is referenced in https://github.com/mmstick/cargo-deb/blob/master/README.md.

```
"libc6 (>= 2.2.1), exim | mail-transport-agent"
```

What's the recommended way to actually provide dependencies right now? Imho the simplest approach would be to test for `$auto` or just pass the string literal as is.

**Comment by pornel** [comment]
Fixed in fd073aedd9f3a1095cafd3a8e07755c700e319bf

it's still naive, but at least uses commas as it should have.
