### ISSUE TITLE
Run dpkg through sudo if --install is specified

### ISSUE THREAD

**Issue by clarcharr** [mmstick/cargo-deb#28]
This is generally better for security reasons to not run cargo via root, and it also works well with rustup.

**Comment by pornel** [comment]
Thanks. Do you think it's fine to unconditionally use sudo? Skip it if uid == 0?

**Comment by clarcharr** [comment]
Skipping for root is always alright, although not too necessary. It works as a workaround if sudo isn't installed.

**Comment by pornel** [comment]
Done
