### ISSUE TITLE
Thoughts on how to handle cross compilation

### ISSUE THREAD

**Issue by superlupo12** [mmstick/cargo-deb#3]
Rust/cargo make cross compilation quite easy. Just install a target std with multirust/rustup, and build like this:
`cargo build --release --target $some-rust-target-triplet`
The results are then in `target/$some-rust-target-triplet/release/example-binary`.
Maybe cargo-deb should also accept the target flag, somehow take the assets from the right target subdirectory, and "guess" the dpkg architecture.

**Comment by pornel** [comment]
Done. Try the latest version from `master`.

```sh
cargo deb --target=$triple
```

**Comment by herrernst** [comment]
Thanks. A quick test: stripping fails. With `--no-strip`, it finishes.
```
root@debian-jessie-chroot:~# cargo new --bin rust-example-bin
     Created binary (application) `rust-example-bin` project
root@debian-jessie-chroot:~# cd rust-example-bin
root@debian-jessie-chroot:~/rust-example-bin# cargo deb --target=arm-unknown-linux-gnueabihf 
warning: description field is missing in Cargo.toml
warning: license field is missing in Cargo.toml
   Compiling rust-example-bin v0.1.0 (file:///root/rust-example-bin)
    Finished release [optimized] target(s) in 0.57 secs
strip: Unable to recognise the format of the input file `/root/rust-example-bin/target/arm-unknown-linux-gnueabihf/release/rust-example-bin'
cargo-deb: strip failed: /root/rust-example-bin/target/arm-unknown-linux-gnueabihf/release/rust-example-bin
root@debian-jessie-chroot:~/rust-example-bin# cargo deb --target=arm-unknown-linux-gnueabihf --no-strip
warning: description field is missing in Cargo.toml
warning: license field is missing in Cargo.toml
    Finished release [optimized] target(s) in 0.0 secs
ar: creating rust-example-bin_0.1.0_armhf.deb
root@debian-jessie-chroot:~/rust-example-bin# 
```
How to I get it to use `arm-linux-gnueabihf-strip`? (I only have `linker` set up in `~/.cargo/config`)

**Comment by pornel** [comment]
I don't know how to find the right strip command. Is there a general naming scheme? Is it provided by Rust/Rustup, or Debian?

**Comment by herrernst** [comment]
I don't think there is a consistent naming scheme to get this automatically. I'll just strip manually if needed before packing when cross-compiling.

**Comment by pornel** [comment]
I think I could read the linker from `.cargo/config` and assume strip uses the same naming scheme.

**Comment by pornel** [comment]
I've added support for [target.$triple] strip = … in .cargo/config

**Comment by herrernst** [comment]
Works, thanks!
