### ISSUE TITLE
Unsupported compression options (on 32 bit)

### ISSUE THREAD

**Issue by beedaddy** [mmstick/cargo-deb#34]
I've two VMs with Debian Stretch 64bit and Debian Stretch 32bit. On the 64bit VM, everything's fine. But on the 32bit VM, I get the following error:

```
cargo deb: IO error  
  because: unsupported compression options
```
I'm pretty sure that the setup of both VMs is the same (except the architecture).

**Comment by pornel** [comment]
Is that because of LZMA? Try compiling cargo-deb with `--no-default-features` to disable LZMA.

**Comment by pornel** [comment]
Ah, this may be it: https://github.com/fpgaminer/rust-lzma/pull/12

**Comment by pornel** [comment]
I've pushed change to master, try that.

**Comment by beedaddy** [comment]
Yes, that was the problem. Your workaround in master solved it. Thanks a lot!
