### ISSUE TITLE
fe1f4d12 broke cargo build --release

### ISSUE THREAD

**Issue by Drakulix** [mmstick/cargo-deb#4]
panic = "abort" is incompatible with pkg-config resulting in the following error when compiling with release flag:

```
error: the crate `pkg_config` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`
```

This also break cargo install --git, as cargo install uses release by default.

Please fix and consider adding --release to travis builds.

**Comment by mmstick** [comment]
You should perform `cargo clean` as it builds fine here with `cargo build --release`.

**Comment by Drakulix** [comment]
This was happening in an empty container with cargo install --git <this repository>
I have no idea, if cargo install handels this any differently.
