### ISSUE TITLE
Build src deb

### ISSUE THREAD

**Issue by spacekookie** [mmstick/cargo-deb#40]
I want to easily put my software into a ppa, which requires me to build a src deb. I'm not super experienced with debian packaging but that sounds like the kind of thing that could be a by-product of this crate?

Is that possible?

**Comment by messense** [comment]
FYI, [Structure of a Source Package](https://debian-handbook.info/browse/stable/sect.source-package-structure.html), should be possible to implement it in cargo-deb I think?

**Comment by kornelski** [comment]
Currently cargo-deb can't make source packages.

I wouldn't mind developing such functionality, but I don't know enough about Debian's requirements for the source packages. 

My problem is that there's a lot of documentation for deb-src packages, but it's hard to know which ones are up to date and relevant for Rust. Also lots of deb guides assume you use existing Perl-based tooling, but I think having Cargo-deb being pure Rust is much easier for Rust users.

Can you help figuring out how does Debian prefer Rust source packages to be structured and built? Is there an existing good Rust-based project in Debian that I could look at?

**Comment by mmstick** [comment]
@kornelski There's this one: https://github.com/pop-os/distinst

**Comment by infinity0** [comment]
For source (official) Debian packages see

- https://crates.io/crates/debcargo
- https://anonscm.debian.org/cgit/pkg-rust/debcargo.git/
- https://wiki.debian.org/Teams/RustPackaging/Policy

**Comment by kornelski** [comment]
I'm going to leave out src packages. There's https://lib.rs/crates/debcargo for this.
