### ISSUE TITLE
`assets` belongs to metadata.deb rather than package.metadata.deb

### ISSUE THREAD

**Issue by HongxuChen** [mmstick/cargo-deb#44]
It seems that `assets` should be specified under `metadata.deb` rather than `package.metadata.deb` in order to be correctly parsed.

**Comment by HongxuChen** [comment]
It seems that `$auto` dependency generation read binary from `metadata.deb`, however the assets are actually specified by `package.metadata.deb`.

**Comment by kornelski** [comment]
The syntax is `[package.metadata.deb]`: https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table-optional

this makes `deb` table in `metadata` table in `package` table. Assets are read from:

```rust
        let mut deb = self.package.metadata.take().and_then(|m|m.deb)
            .unwrap_or_else(CargoDeb::default);
…
        let assets = self.take_assets(&config, deb.assets.take(), &root_package.targets, readme)?;
```

So I think it's fine.

**Comment by HongxuChen** [comment]
But for `$auto` dependency generation, it seems that when only specified in `[metadata.deb]`, it can analyze the entries of the assets correctly. Or am I missing something?

**Comment by kornelski** [comment]
`[metadata.deb]` behaves 100% identical to `[neat.avocado]` and `[plastic.mighty.ants]` sections. It doesn't do anything.

**Comment by HongxuChen** [comment]
But when I specify `assets` under `[package.metadata.deb]`, `$auto` always gives an empty dependency list.

**Comment by kornelski** [comment]
That's most likely because paths in your assets array are incorrect and it doesn't find them.

**Comment by HongxuChen** [comment]
But strangely enough when I put `assets` under `[metadata.deb]` it found correctly.

**Comment by kornelski** [comment]
Yes, that is because putting `assets` in `[metadata.deb]` is exactly the same as deleting it.

**Comment by kornelski** [comment]
Please rename `[metadata.deb]` to `[this.does.not.work]` and compare the difference.

**Comment by HongxuChen** [comment]
Okay now I figured out, it's my mistake: the path of the entries to be installed should be relative to the *top root directory* rather than the directory containing the current Cargo.toml (as one of the workspaces).

This is a bit unintuitive since each workspace usually defines its own `[package]` and consequently `[package.metadata.deb]` is better defined inside the workspace's Cargo.toml; the path relative to the root Cargo.toml's parent directory is a little confusing.

Maybe mention a little this issue in the README?

**Comment by HongxuChen** [comment]
I just noticed that for the other entries that are *not* inside `target/release`, the path is still relative to *current* Cargo.toml's parent directory. I think there should be some fixes for this.
