### ISSUE TITLE
Allow $CARGO_TARGET_DIR substitution in assets config

### ISSUE THREAD

**Issue by RReverser** [mmstick/cargo-deb#48]
We override CARGO_TARGET_DIR to prebuild dependencies in cached Docker layer and later to reuse them during regular builds. Right now it doesn't seem possible to encode environment-dependant path in assets property, but it would be nice to at least for this particular usecase.

**Comment by RReverser** [comment]
Alternative could be allowing to pass paths to additional assets as command-line arguments.

**Comment by kornelski** [comment]
It's probably not documented, but we automagically fix "target/release" to mean whatever the real target dir actually is.

I've tried this:

```sh
 CARGO_TARGET_DIR=/tmp/xxx cargo deb
```

and it has properly built itself in `/tmp/xxx/debian/cargo-deb_1.4.0_amd64.deb` from `/tmp/xxx/release/cargo-deb`.

**Comment by kornelski** [comment]
71e2d894a6cb05a599bfebf1dff6fa94b8b85ff0

**Comment by RReverser** [comment]
Ohh, it did build for me in CARGO_TARGET_DIR but didn't search it as I had `../target/release/...` in assets (as it was Cargo.toml of a crate in a workspace). I'll give it another shot with just `target/` tomorrow.

**Comment by kornelski** [comment]
Speaking of workspaces, I'm not sure how should they look from debian perspective: #49

**Comment by RReverser** [comment]
@kornelski Thanks, that worked.
