### ISSUE TITLE
Support for package transition flags

### ISSUE THREAD

**Issue by fredszaq** [mmstick/cargo-deb#50]
Hi ! I there any way to add flags to the debian control to help debian package management with package transitions ? (in my case I've renamed my package) 

I should add the folowing flags to my control file (as per 
https://wiki.debian.org/PackageTransition )

```
Breaks: 
Replaces: 
Provides: 
```

But I can seem to find any way to do it with `cargo-deb`

**Comment by kornelski** [comment]
I've added these fileds.

**Comment by fredszaq** [comment]
wow that fast fast ! thanks a lot !
