### ISSUE TITLE
Assets' glob should be resolved after build

### ISSUE THREAD

**Issue by kornelski** [mmstick/cargo-deb#54]
06d78afa0c8f77d686801992ae058c8dc437978b only partially fixes #52 

Config with assets is built first, but assets need to have paths at that point, which creates a chicken-egg problem, because build depends on the config.

So either assets have to be computed in a separate post-build step, or maybe there should be a special glob type for assets? #53

**Comment by ivy** [comment]
Seconding this. I have several binaries in `target/release/` that are only built depending on different environments. It'd be much easier to include them with a glob pattern but unfortunately fails for the first build and succeeds with the next (since the glob will then resolve).
