### ISSUE TITLE
Assets path are resolved relative to workspace dir instead of Cargo.toml dir

### ISSUE THREAD

**Issue by fredszaq** [mmstick/cargo-deb#58]
Hi,
Since the last version, there is as behaviour change in the way assets are resolved where the project `cargo-deb` is runing on is is a workspace

Here is a sample dir hierarchy with a project in a workspace

```
workspace-dir
    |--> debified-project
    |         |--> src
    |         |--> resources
    |         |         \-> stuff.json
    |         \--> Cargo.toml
    |--> other-workspace-project
    \--> Cargo.toml
```
(I run `cargo-deb` on the `debified-project` with a `(cd debified-project && cargo-deb)` )

In previous versions, to include `stuff.json` in the deb I had to add this line to the `[package.metadata.deb]`  of the `Cargo.toml` of `debified-project`
```
assets = [ [ "resources/stuff.json", "/usr/share", 644 ] ]
```

with the last versions (I suspect commit https://github.com/mmstick/cargo-deb/commit/dabd655ef83f777933be1e73ad4a3c339874eafb ) I now need to write this
```
assets = [ [ "debified-project/resources/stuff.json", "/usr/share", 644 ] ]
```
The root dir used to resolve assets  is now the root of the workspace and not the root of the project. I'm not sure it is a good idea because: 
 - Files to be included are most likely in the project dir (and it it is not the case `..` is your friend)
 - In other places in Cargo.toml where path are supplied they are relative to the project and not the workspace (for example the `path` of a depencency)
 - Behaviour changes whether the project is included in the workspace or not, which doesn't smell good

Is it possible to get back to the previous behaviour ?

**Comment by kornelski** [comment]
`cargo metadata` command makes workspaces look almost like a single project, which is why cargo-deb works with them at all.

But currently there's no explicit support for workspaces, because I don't know how it even should look like: #49

**Comment by kornelski** [comment]
I can't reproduce it with the latest version. Can you try it with 1.8.0?

If it still happens, can you share a minimal test case?

**Comment by fredszaq** [comment]
sure thing ! there you go !

https://github.com/fredszaq/cargo-deb-workspace-problem

**Comment by kornelski** [comment]
Thanks for the test case. It should work now.

**Comment by fredszaq** [comment]
Works like a charm ! thanks a lot !
