### ISSUE TITLE
profile.XXX.debug can be u32 or bool 

### ISSUE THREAD

**Issue by enizor** [mmstick/cargo-deb#68]
https://github.com/mmstick/cargo-deb/blob/4bd257dbd9700b1b587619c0938f2013e6e25e0d/src/manifest.rs#L405

Actually it can be an `u32` ([cargo code](https://github.com/rust-lang/cargo/blob/558eee4fbca56bdc4969e114ed2cc4ed7c3913bb/src/cargo/core/profiles.rs#L349))

I did not totallly understand your `fn strip_binaries()`, but I think it should be fine to cast a `0` to `false` and any other integer to `true`.

I will create a PR if this behavior suits you.

**Comment by kornelski** [comment]
Yes, indeed, our parsing is not as flexible as Cargo's. Please make a PR.
