### ISSUE TITLE
objcopy needs to be parameterizable for cross-compilation suddenly?

### ISSUE THREAD

**Issue by alexpdp7** [mmstick/cargo-deb#87]
Hi,

I suck at packaging, so maybe I'm doing all this horrendously wrong.

I was using:

https://github.com/alexpdp7/ragent/blob/d1b5fa2393c88b677c758a27be0d1926a0ff4682/packages/debian_stretch_rpi3/Dockerfile
https://github.com/alexpdp7/ragent/blob/d1b5fa2393c88b677c758a27be0d1926a0ff4682/packages/debian_stretch_rpi3/cargo_config

to crosscompile debs for a Raspberry Pi 3, but suddenly I'm getting:

```
objcopy: Unable to recognise the format of the input file `/root/src/target/armv7-unknown-linux-gnueabihf/release/check_ragent'
cargo-deb: Command objcopy failed to launch
  because: exit code: 1
```

I've hacked it doing

```
+RUN cp /usr/bin/arm-linux-gnueabihf-objcopy /usr/bin/objcopy
```

on my `Dockerfile`, but this doesn't look very neat.

I don't understand why this is suddenly required, but maybe objcopy should be tunable like linker and strip?

**Comment by kornelski** [comment]
Yup, it should be configurable

**Comment by kornelski** [comment]
Could you make a PR for this?

You could copy the code that we use for making strip configurable.
