### ISSUE TITLE
Asset source dir not recursively copied

### ISSUE THREAD

**Issue by apiraino** [mmstick/cargo-deb#90]
Hey,

first of all, thanks for this very useful cargo extension! :+1: 

Now, something I don't fully understand. I would like to copy all migrations:
```
$ tree migrations/
migrations/
├── 2018-06-03-132600_create_users
│   ├── down.sql
│   └── up.sql
└── 2018-08-10-151755_create_doors
    ├── down.sql
    └── up.sql

2 directories, 4 files
```

This does not copy recursively:
```
assets = [
    ["migrations/", "migrations/", "755"],
]
```

This works:
```
assets = [
    ["migrations/*/*", "migrations/", "755"],
]
```

bug or feature? :-)

Thanks!

**Comment by kornelski** [comment]
It's sort-of a feature. We use a simple `glob()` that does a shallow directory scan.

**Comment by apiraino** [comment]
ok, I think that makes sense. The other way around would require more thought (f.e. someone may want a recursive scan but with exceptions).
