### ISSUE TITLE
systemd example

### ISSUE THREAD

**Issue by GopherJ** [mmstick/cargo-deb#92]
Hello, I would like to use `cargo-deb` to replace my `bash` script. I need `openssl` and someother `dev` packages as dependencies. 

At the same time, I would like to be able to manage my application using systemd (status, stop, start...).

I also have `Config.toml` which should be put together with the binary.

Could you please give me some information on how to achieve this using `cargo-deb`? thanks!

**Comment by kornelski** [comment]
You'd use 

```toml
depends = "$auto, systemd, openssl, someother-dev"
```

we have systemd example here:

https://github.com/mmstick/cargo-deb#example-of-custom-cargotoml-additions

**Comment by GopherJ** [comment]
@kornelski  Hello, thanks that basically works, I just get some warning like this:

```
warning: ldd (/home/cheng/Project/Ubudu/ACS/server/Config.toml):  (no auto deps for /home/cheng/Project/Ubudu/ACS/server/Config.toml)
warning: ldd (/home/cheng/Project/Ubudu/ACS/server/tls/cert.pem):  (no auto deps for /home/cheng/Project/Ubudu/ACS/server/tls/cert.pem)
warning: ldd (/home/cheng/Project/Ubudu/ACS/server/target/x86_64-unknown-linux-musl/debug/acs_server):  (no auto deps for /home/cheng/Project/Ubudu/ACS/server/target/x86_64-unknown-linux-musl/debug/acs_server)
```
do you know how to remove them?

**Comment by GopherJ** [comment]
and also I specified already the `license-file` file both in package meta and deb meta, still got this warning:

```
warning: license field is missing in Cargo.toml
```

Any way there is no error and it works perfeclty, hope you can let me know what's the cause for this type of warning.
Thank you for the great work!

**Comment by ximon18** [comment]
The systemd example only seems to be a dependency on systemd, not an example of making your application manageable as a systemd unit. I'm looking at this right now and you seem to need a unit file asset and a postinst maintenance-script (the latter if you want the unit enabled or maybe even started).

Unfortunately the unit file content is dependent on which systemd version the target O/S supports, e.g. Ubuntu 16.04 and Ubuntu 18.04 don't support `Type=exec` as that was introduced in a more recent version of systemd than is bundled with those O/S versions, similar story with Debian releases.

What I haven't worked out is how to use cargo deb to build packages for different O/S target versions, the only way I can currently imagine is to use additional Cargo.toml files which will be a lot of copy/pasting to maintain!

**Comment by ximon18** [comment]
So I just came across https://github.com/mmstick/cargo-deb/issues/100 which relates to this. Additionally I just discovered `cargo deb --variant` described in the `--help` as "Alternative configuraiton section to use" which would avoid the need for duplicate Cargo.toml files when building DEBs for different target operaitng systems, but still require a duplicate Cargo deb config sections.

**Comment by kornelski** [comment]
https://github.com/mmstick/cargo-deb/blob/master/systemd.md
