### ISSUE TITLE
Allow use of assets with default behavior.

### ISSUE THREAD

**Issue by nexoscp** [mmstick/cargo-deb#93]
Hello @mmstick,

thx for building cargo-deb! 
It would be great to have a switch so that adding assets keeps the default behavior. Could be named something like "additional-assets" or so.

Have a nice day!

**Comment by kornelski** [comment]
We already have a magic `$auto` value for dependencies. Perhaps we could do the same and allow `$auto` in the assets?

Would you like to give a try implementing this?
