### ISSUE TITLE
gzipping manpage

### ISSUE THREAD

**Issue by bestouff** [mmstick/cargo-deb#97]
Apparently under debian all manpages under `/usr/shame/man` are gzipped. How about a command to gzip assets, or a special "manpage" command ?

**Comment by kornelski** [comment]
Yeah, sounds like a good idea. I'm not sure how much to make it manual vs magic. For example, we could automatically gzip stuff put in `/usr/share/man`, or autogzip when target filename ends in `*.gz`.

**Comment by bestouff** [comment]
The autogzip feature sounds cool. I'm trying to find why it could explode in flight, but it seems legit.

**Comment by Kixunil** [comment]
This should be considered in case #106 gets implemented.
